import { useCallback, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link, useFocusEffect, type Href } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppBottomNav } from '../components/app-bottom-nav';
import { loadPlans, ProjectPlan } from '../lib/project-storage';

export default function DashboardScreen() {
  const [plans, setPlans] = useState<ProjectPlan[]>([]);
  useFocusEffect(useCallback(() => { loadPlans().then(setPlans); }, []));
  const stats = useMemo(() => ({ tasks: plans.flatMap(p => p.tasks).filter(t => t.done).length, totalTasks: plans.flatMap(p => p.tasks).length, milestones: plans.flatMap(p => p.milestones).filter(m => m.done).length, totalMilestones: plans.flatMap(p => p.milestones).length }), [plans]);
  const recent = plans[0];
  return <View style={styles.shell}><ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.hero}><SafeAreaView edges={['top']}><Text style={styles.brand}>APP PROJECT PLANNER</Text><Text style={styles.title}>Turn ideas into an actionable roadmap.</Text><Text style={styles.heroCopy}>Plan requirements, prioritize work, track budgets and milestones, and keep every app project moving.</Text><Link href={'/planner' as Href} asChild><Pressable style={styles.primary}><Text style={styles.primaryText}>+ Create project</Text></Pressable></Link></SafeAreaView></View>
    <View style={styles.body}>
      <Text style={styles.sectionTitle}>Workspace overview</Text><View style={styles.statGrid}><Stat value={`${plans.length}`} label="Projects"/><Stat value={`${stats.tasks}/${stats.totalTasks}`} label="Tasks done"/><Stat value={`${stats.milestones}/${stats.totalMilestones}`} label="Milestones"/></View>
      {recent ? <><Text style={styles.sectionTitle}>Continue planning</Text><Link href={`/project/${recent.id}` as Href} asChild><Pressable style={styles.project}><View style={styles.row}><Text style={styles.projectName}>{recent.name}</Text><Text style={styles.chevron}>›</Text></View><Text style={styles.meta}>{recent.status} · {recent.type}</Text><View style={styles.progressTrack}><View style={[styles.progressFill,{width:`${Math.round((recent.checklist.filter(Boolean).length/checklistSize)*100)}%`}]} /></View><Text style={styles.progressText}>{recent.checklist.filter(Boolean).length}/{checklistSize} readiness checks complete</Text></Pressable></Link></> : <View style={styles.empty}><Text style={styles.emptyTitle}>Start with your first project</Text><Text style={styles.emptyCopy}>Create a reusable project workspace with tasks, milestones, budgets, requirements, and launch checks.</Text></View>}
      <Text style={styles.sectionTitle}>Quick actions</Text><View style={styles.actions}><Link href={'/projects' as Href} asChild><Pressable style={styles.action}><Text style={styles.actionIcon}>▣</Text><Text style={styles.actionTitle}>My projects</Text><Text style={styles.actionCopy}>Review every active workspace</Text></Pressable></Link><Link href={'/resources' as Href} asChild><Pressable style={styles.action}><Text style={styles.actionIcon}>≡</Text><Text style={styles.actionTitle}>Planning resources</Text><Text style={styles.actionCopy}>Use templates and prompts</Text></Pressable></Link></View>
    </View>
  </ScrollView><AppBottomNav active="/"/></View>;
}
const checklistSize=5;
function Stat({value,label}:{value:string;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
const styles=StyleSheet.create({shell:{flex:1,backgroundColor:'#F8FAFC'},screen:{flex:1},content:{paddingBottom:35},hero:{backgroundColor:'#111827',paddingHorizontal:24,paddingBottom:38},brand:{color:'#F4C95D',fontSize:12,fontWeight:'900',letterSpacing:1.5,marginTop:18},title:{color:'#FFF',fontSize:38,lineHeight:44,fontWeight:'900',marginTop:15},heroCopy:{color:'#CBD5E1',fontSize:16,lineHeight:25,marginTop:14},primary:{backgroundColor:'#F4C95D',padding:16,borderRadius:13,alignItems:'center',marginTop:24},primaryText:{color:'#111827',fontSize:16,fontWeight:'900'},body:{padding:22},sectionTitle:{color:'#111827',fontSize:22,fontWeight:'900',marginTop:24,marginBottom:13},statGrid:{flexDirection:'row',gap:9},stat:{flex:1,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:14,padding:14},statValue:{color:'#111827',fontSize:22,fontWeight:'900'},statLabel:{color:'#64748B',fontSize:11,fontWeight:'700',marginTop:4},project:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:17,padding:18},row:{flexDirection:'row',alignItems:'center'},projectName:{color:'#111827',fontSize:20,fontWeight:'900',flex:1},chevron:{color:'#64748B',fontSize:28},meta:{color:'#64748B',fontSize:14,marginTop:4},progressTrack:{height:8,backgroundColor:'#E2E8F0',borderRadius:4,marginTop:16,overflow:'hidden'},progressFill:{height:8,backgroundColor:'#D19A16'},progressText:{color:'#64748B',fontSize:12,fontWeight:'700',marginTop:7},empty:{backgroundColor:'#FFFBEB',borderColor:'#F4C95D',borderWidth:1,borderRadius:17,padding:20},emptyTitle:{color:'#111827',fontSize:19,fontWeight:'900'},emptyCopy:{color:'#475569',fontSize:15,lineHeight:23,marginTop:8},actions:{gap:10},action:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:15,padding:17},actionIcon:{color:'#9A6B00',fontSize:22,fontWeight:'900'},actionTitle:{color:'#111827',fontSize:17,fontWeight:'900',marginTop:7},actionCopy:{color:'#64748B',fontSize:14,marginTop:4}});
