import { useCallback, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link, useFocusEffect, type Href } from 'expo-router';
import { AppBottomNav } from '../components/app-bottom-nav';
import { ProjectPlan, loadPlans } from '../lib/project-storage';

const filters=['All','Idea','Planning','In progress','Ready to launch'];
export default function ProjectsScreen(){const [plans,setPlans]=useState<ProjectPlan[]>([]);const [filter,setFilter]=useState('All');useFocusEffect(useCallback(()=>{loadPlans().then(setPlans);},[]));const shown=useMemo(()=>filter==='All'?plans:plans.filter(p=>p.status===filter),[filter,plans]);return <View style={styles.shell}><ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>PROJECT WORKSPACES</Text><Text style={styles.title}>My projects</Text><Text style={styles.intro}>Track requirements, tasks, milestones, budgets, and launch readiness in one place.</Text><Link href={'/planner' as Href} asChild><Pressable style={styles.newButton}><Text style={styles.newText}>+ New project</Text></Pressable></Link><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map(item=><Pressable key={item} onPress={()=>setFilter(item)} style={[styles.filter,filter===item&&styles.filterOn]}><Text style={[styles.filterText,filter===item&&styles.filterTextOn]}>{item}</Text></Pressable>)}</ScrollView>{shown.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No projects in this view</Text><Text style={styles.emptyCopy}>Create a project or select a different status filter.</Text></View>:shown.map(plan=><Link key={plan.id} href={`/project/${plan.id}` as Href} asChild><Pressable style={styles.card}><View style={styles.cardTop}><Text style={styles.cardTitle}>{plan.name}</Text><Text style={styles.arrow}>›</Text></View><Text style={styles.status}>{plan.status}</Text><Text style={styles.meta}>{plan.type} · {plan.platforms.join(', ')}</Text><View style={styles.metrics}><Text style={styles.metric}>{plan.tasks.filter(t=>t.done).length}/{plan.tasks.length} tasks</Text><Text style={styles.metric}>{plan.milestones.filter(m=>m.done).length}/{plan.milestones.length} milestones</Text><Text style={styles.metric}>{plan.checklist.filter(Boolean).length}/5 ready</Text></View></Pressable></Link>)}</ScrollView><AppBottomNav active="/projects"/></View>}
const styles=StyleSheet.create({shell:{flex:1,backgroundColor:'#F8FAFC'},screen:{flex:1},content:{padding:24,paddingBottom:45},eyebrow:{color:'#9A6B00',fontSize:12,fontWeight:'900',letterSpacing:1.4},title:{color:'#111827',fontSize:34,fontWeight:'900',marginTop:8},intro:{color:'#475569',fontSize:16,lineHeight:25,marginTop:8},newButton:{backgroundColor:'#111827',borderRadius:13,padding:15,alignItems:'center',marginTop:20},newText:{color:'#FFF',fontSize:16,fontWeight:'900'},filters:{gap:8,paddingVertical:18},filter:{backgroundColor:'#E2E8F0',paddingHorizontal:13,paddingVertical:9,borderRadius:999},filterOn:{backgroundColor:'#F4C95D'},filterText:{color:'#475569',fontSize:13,fontWeight:'700'},filterTextOn:{color:'#111827'},empty:{backgroundColor:'#FFF',borderColor:'#E2E8F0',borderWidth:1,borderRadius:16,padding:24},emptyTitle:{color:'#111827',fontSize:19,fontWeight:'900'},emptyCopy:{color:'#64748B',marginTop:7},card:{backgroundColor:'#FFF',borderColor:'#E2E8F0',borderWidth:1,borderRadius:16,padding:18,marginBottom:12},cardTop:{flexDirection:'row',alignItems:'center'},cardTitle:{color:'#111827',fontSize:20,fontWeight:'900',flex:1},arrow:{fontSize:28,color:'#64748B'},status:{alignSelf:'flex-start',backgroundColor:'#FFFBEB',color:'#8A6200',fontSize:12,fontWeight:'800',paddingHorizontal:9,paddingVertical:5,borderRadius:999,marginTop:7},meta:{color:'#64748B',fontSize:13,marginTop:10},metrics:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:13},metric:{color:'#334155',backgroundColor:'#F1F5F9',fontSize:11,fontWeight:'700',paddingHorizontal:9,paddingVertical:6,borderRadius:999}});
