import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppBottomNav } from '../components/app-bottom-nav';

const resources=[
  {title:'Problem statement',prompt:'For [target user], the problem is [specific pain]. Our product will [solution] so they can [measurable outcome].'},
  {title:'User story',prompt:'As a [type of user], I want to [action] so that [benefit]. Acceptance criteria: [observable result].'},
  {title:'Feature priority',prompt:'Must have: required for the core outcome. Should have: high value but not launch-critical. Could have: useful enhancement. Later: intentionally deferred.'},
  {title:'Milestone definition',prompt:'Milestone name · intended outcome · owner · target date · completion evidence · known dependencies.'},
  {title:'Launch decision',prompt:'Who is the first audience? What problem is solved? What must be measured? What support exists? What would block launch?'},
];
export default function ResourcesScreen(){return <View style={styles.shell}><ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>PLANNING LIBRARY</Text><Text style={styles.title}>Reusable project prompts</Text><Text style={styles.intro}>Use these frameworks to make requirements clearer before design and development begin.</Text>{resources.map((item,index)=><View key={item.title} style={styles.card}><Text style={styles.number}>{String(index+1).padStart(2,'0')}</Text><Text style={styles.cardTitle}>{item.title}</Text><Text selectable style={styles.prompt}>{item.prompt}</Text></View>)}<View style={styles.guide}><Text style={styles.guideTitle}>A strong first release</Text><Text style={styles.guideText}>Focus on one audience, one painful problem, and one complete workflow. Move everything else into later milestones. A smaller coherent release is easier to test than a broad incomplete one.</Text></View></ScrollView><AppBottomNav active="/resources"/></View>}
const styles=StyleSheet.create({shell:{flex:1,backgroundColor:'#F8FAFC'},screen:{flex:1},content:{padding:24,paddingBottom:45},eyebrow:{color:'#9A6B00',fontSize:12,fontWeight:'900',letterSpacing:1.4},title:{color:'#111827',fontSize:34,fontWeight:'900',marginTop:8},intro:{color:'#475569',fontSize:16,lineHeight:25,marginTop:9,marginBottom:18},card:{backgroundColor:'#FFF',borderColor:'#E2E8F0',borderWidth:1,borderRadius:16,padding:19,marginBottom:12},number:{color:'#9A6B00',fontSize:11,fontWeight:'900',letterSpacing:1.2},cardTitle:{color:'#111827',fontSize:19,fontWeight:'900',marginTop:6},prompt:{color:'#475569',fontSize:15,lineHeight:23,marginTop:9},guide:{backgroundColor:'#111827',borderRadius:17,padding:21,marginTop:12},guideTitle:{color:'#F4C95D',fontSize:19,fontWeight:'900'},guideText:{color:'#CBD5E1',fontSize:15,lineHeight:23,marginTop:9}});
