import { Image, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link, useLocalSearchParams, type Href } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getProject } from '../../data/portfolio';

export default function CaseStudyScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const project = getProject(slug);
  if (!project) return <SafeAreaView style={styles.missing}><Text style={styles.title}>Case study not found.</Text><Link href={'/portfolio' as Href}>Return to portfolio</Link></SafeAreaView>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={[styles.hero,{backgroundColor:project.accent}]}><SafeAreaView edges={['top']}><Text style={styles.eyebrow}>{project.featured?'FLAGSHIP CASE STUDY':'CASE STUDY'}</Text><Text style={styles.heroTitle}>{project.name}</Text><Text style={styles.heroTagline}>{project.tagline}</Text><Image source={project.image} style={styles.image} resizeMode="cover"/></SafeAreaView></View>
    <View style={styles.body}><Section title="Overview"><Text style={styles.copy}>{project.summary}</Text></Section><Section title="The challenge"><Text style={styles.copy}>{project.challenge}</Text></Section><Section title="The solution"><Text style={styles.copy}>{project.solution}</Text></Section><Section title="Key capabilities">{project.features.map(feature=><View key={feature} style={styles.feature}><Text style={[styles.check,{color:project.accent}]}>✓</Text><Text style={styles.featureText}>{feature}</Text></View>)}</Section><Section title="Technology"><View style={styles.techRow}>{project.tech.map(item=><Text key={item} style={styles.tech}>{item}</Text>)}</View></Section>
      {project.appUrl?<Pressable style={[styles.primary,{backgroundColor:project.accent}]} onPress={()=>Linking.openURL(project.appUrl!)}><Text style={styles.primaryText}>Open Sports Analytics ↗</Text></Pressable>:null}
      <Link href="/consultation" asChild><Pressable style={styles.consult}><Text style={styles.consultText}>Build an app like this</Text></Pressable></Link><Link href={'/portfolio' as Href} asChild><Pressable><Text style={styles.back}>← Back to portfolio</Text></Pressable></Link>
    </View>
  </ScrollView>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F8FAFC'},content:{paddingBottom:40},hero:{paddingHorizontal:20,paddingBottom:30},eyebrow:{color:'#FFF',fontSize:11,fontWeight:'900',letterSpacing:1.6,marginTop:18,opacity:.85},heroTitle:{color:'#FFF',fontSize:40,fontWeight:'900',marginTop:8},heroTagline:{color:'#FFF',fontSize:18,lineHeight:26,fontWeight:'700',marginTop:7,opacity:.92},image:{width:'100%',height:230,borderRadius:18,marginTop:24,backgroundColor:'#FFF'},body:{padding:22},section:{marginBottom:32},sectionTitle:{color:'#111827',fontSize:24,fontWeight:'900',marginBottom:12},copy:{color:'#475569',fontSize:16,lineHeight:26},feature:{flexDirection:'row',gap:11,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',padding:15,borderRadius:12,marginBottom:9},check:{fontSize:17,fontWeight:'900'},featureText:{flex:1,color:'#334155',fontSize:15,fontWeight:'700',lineHeight:21},techRow:{flexDirection:'row',flexWrap:'wrap',gap:8},tech:{color:'#312E81',backgroundColor:'#EEF2FF',paddingHorizontal:12,paddingVertical:8,borderRadius:999,fontSize:13,fontWeight:'800'},primary:{padding:16,borderRadius:13,alignItems:'center',marginBottom:12},primaryText:{color:'#FFF',fontSize:16,fontWeight:'900'},consult:{padding:15,borderRadius:13,alignItems:'center',borderWidth:2,borderColor:'#111827'},consultText:{color:'#111827',fontSize:16,fontWeight:'900'},back:{color:'#475569',fontSize:15,fontWeight:'800',textAlign:'center',marginTop:24},missing:{flex:1,padding:24,justifyContent:'center'},title:{fontSize:28,fontWeight:'900',marginBottom:18}});
