import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { checklistLabels, formatMoney, loadPlans, ProjectPlan, removePlan, savePlan } from '../../lib/project-storage';

export default function ProjectDetail(){const {id}=useLocalSearchParams<{id:string}>();const [plan,setPlan]=useState<ProjectPlan>();useFocusEffect(useCallback(()=>{loadPlans().then(plans=>setPlan(plans.find(p=>p.id===id)));},[id]));if(!plan)return <View style={styles.center}><Text>Loading project…</Text></View>;const current=plan;
  async function toggle(index:number){const checklist=current.checklist.map((v,i)=>i===index?!v:v);const next:ProjectPlan={...current,checklist,updatedAt:new Date().toISOString()};setPlan(next);await savePlan(next)}
  async function share(){const features=current.features.length?current.features.join(', '):'To be defined';await Share.share({title:`${current.name} app brief`,message:`${current.name}\n\nAudience: ${current.audience}\nProduct: ${current.type}\nPlatforms: ${current.platforms.join(', ')}\nFeatures: ${features}\nPlanning range: ${formatMoney(current.estimateLow)}–${formatMoney(current.estimateHigh)}\nTimeline: ${current.weeksLow}–${current.weeksHigh} weeks\n\nNotes: ${current.notes||'None'}\n\nCreated with ImagineMyApps Project Planner.`})}
  function confirmDelete(){Alert.alert('Delete project?','This removes the saved brief from this device.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{await removePlan(current.id);router.replace('/projects' as never)}}])}
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>SAVED PROJECT BRIEF</Text><Text style={styles.title}>{current.name}</Text><Text style={styles.audience}>For {current.audience}</Text><View style={styles.range}><Text style={styles.rangeLabel}>PLANNING RANGE</Text><Text style={styles.money}>{formatMoney(current.estimateLow)}–{formatMoney(current.estimateHigh)}</Text><Text style={styles.time}>{current.weeksLow}–{current.weeksHigh} weeks</Text></View><Section title="Product"><Text style={styles.copy}>{current.type}</Text><Text style={styles.copy}>{current.platforms.join(' · ')}</Text></Section><Section title="Must-have features"><View style={styles.tags}>{(current.features.length?current.features:['No features selected yet']).map(f=><Text key={f} style={styles.tag}>{f}</Text>)}</View></Section>{!!current.notes&&<Section title="Notes"><Text style={styles.copy}>{current.notes}</Text></Section>}<Section title="Readiness checklist"><Text style={styles.help}>Tap each item as you validate your plan.</Text>{checklistLabels.map((label,i)=><Pressable key={label} onPress={()=>toggle(i)} style={[styles.checkItem,current.checklist[i]&&styles.checkOn]}><Text style={styles.checkMark}>{current.checklist[i]?'✓':'○'}</Text><Text style={[styles.checkText,current.checklist[i]&&styles.checkTextOn]}>{label}</Text></Pressable>)}</Section><Pressable onPress={share} style={styles.share}><Text style={styles.shareText}>Share project brief</Text></Pressable><Pressable onPress={confirmDelete}><Text style={styles.delete}>Delete project</Text></Pressable><Text style={styles.disclaimer}>Planning ranges are estimates for early discussion and are not quotes or guarantees.</Text></ScrollView>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F8FAFC'},content:{padding:24,paddingBottom:55},center:{flex:1,alignItems:'center',justifyContent:'center'},eyebrow:{color:'#9A6B00',fontSize:12,fontWeight:'900',letterSpacing:1.4},title:{color:'#111827',fontSize:34,fontWeight:'900',marginTop:8},audience:{color:'#475569',fontSize:17,lineHeight:25,marginTop:7},range:{backgroundColor:'#111827',borderRadius:18,padding:21,marginTop:24},rangeLabel:{color:'#F4C95D',fontSize:11,fontWeight:'900',letterSpacing:1.3},money:{color:'#FFF',fontSize:28,fontWeight:'900',marginTop:8},time:{color:'#CBD5E1',fontSize:17,fontWeight:'800',marginTop:5},section:{marginTop:30},sectionTitle:{color:'#111827',fontSize:22,fontWeight:'900',marginBottom:11},copy:{color:'#475569',fontSize:16,lineHeight:25,marginBottom:4},tags:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{backgroundColor:'#E2E8F0',color:'#334155',paddingHorizontal:12,paddingVertical:8,borderRadius:999,fontSize:13,fontWeight:'700'},help:{color:'#64748B',fontSize:14,marginBottom:12},checkItem:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#FFF',borderWidth:1,borderColor:'#CBD5E1',borderRadius:12,padding:15,marginBottom:9},checkOn:{backgroundColor:'#ECFDF5',borderColor:'#10B981'},checkMark:{color:'#047857',fontSize:20,fontWeight:'900'},checkText:{color:'#334155',fontSize:15,fontWeight:'700',flex:1},checkTextOn:{color:'#065F46'},share:{backgroundColor:'#F4C95D',padding:16,borderRadius:13,alignItems:'center',marginTop:30},shareText:{color:'#111827',fontSize:16,fontWeight:'900'},delete:{color:'#B91C1C',fontSize:15,fontWeight:'800',textAlign:'center',padding:18},disclaimer:{color:'#64748B',fontSize:11,lineHeight:17,textAlign:'center'}});
